module.exports = {
    INVALID_REQUEST : "Invalid request",
    BAD_REQUEST:'Bad Request',
    USER_NOT_EXIST: "user not exist",
    USER_EXIST: "user already exist",
    USER_CREATED: "user created successfully",
    USER_EDITED: "user edited successfully",
    INVALID_PASSWORD: "Inavlid Password",
    OTP_SENT: "otp sent successfully",
    OTP_VERIFIED: "otp verified successfully",
    OTP_NOT_VERIFIED: "otp not verified",
    PASSWORD_CHANGED: "password changed successfully",
    INTERNAL_SERVER_ERROR:'Internal Server Error',
    INVALID_CREDENTIALS:'invalid credentials',
    USER_LOGEDIN:'User Logged in sucessfully',
}